### ISSUE TITLE
The vulnerability is a memory leak bug located at line 245 of the file /liblisp/src/io.c

### ISSUE THREAD

**Issue by LuMingYinDetect** [howerj/liblisp#2]
Hello, I am a graduate student specializing in static analysis of programs. Recently, while using a static analysis tool to detect issues in open-source projects, I found several defects in the project. The description of the defects can be found at the following link:https://github.com/LuMingYinDetect/liblisp_defects/blob/main/liblisp_detect_1.md

**Comment by howerj** [comment]
Cheers! This issue should be fixed now.
